# Generated by Django 4.2.5 on 2023-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JPEGArtifactsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_token', models.CharField(max_length=250, verbose_name='Image token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'jpeg artifact image',
                'verbose_name_plural': 'JPEG Artifacts images',
                'db_table': 'jpeg_artifacts_images',
            },
        ),
    ]
