# Generated by Django 4.2.5 on 2023-10-07 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picsart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFunctionsUsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_scales_count', models.IntegerField(default=0, verbose_name='Up scales count')),
                ('bg_deletions_count', models.IntegerField(default=0, verbose_name='Background deletions count')),
                ('jpg_artifacts_deletions_count', models.IntegerField(default=0, verbose_name='JPEG artifacts deletions count')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter_of_usage', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'counter',
                'verbose_name_plural': 'Usage counters',
                'db_table': 'user_functions_usage_counter',
            },
        ),
    ]
