# Generated by Django 4.2.5 on 2023-10-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picsart', '0002_userfunctionsusagecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUserFunctionsUsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_scales_count', models.IntegerField(default=0, verbose_name='Up scales count')),
                ('bg_deletions_count', models.IntegerField(default=0, verbose_name='Background deletions count')),
                ('jpg_artifacts_deletions_count', models.IntegerField(default=0, verbose_name='JPEG artifacts deletions count')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
            ],
            options={
                'verbose_name_plural': 'Usage counters (Anonymous users)',
                'db_table': 'ip_functions_usage_counter',
            },
        ),
        migrations.AlterModelOptions(
            name='userfunctionsusagecounter',
            options={'verbose_name_plural': 'Usage counters (Authenticated users)'},
        ),
    ]
