# Generated by Django 4.2.5 on 2023-10-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picsart', '0004_anonymoususerenhanceslimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususerfunctionsusagecounter',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP Address'),
        ),
    ]
