# Generated by Django 4.2.5 on 2023-10-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picsart', '0005_alter_anonymoususerfunctionsusagecounter_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeEnhancesLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=5, verbose_name='Limit for free using of all features')),
            ],
            options={
                'verbose_name': 'limit',
                'verbose_name_plural': 'Free enhances limit',
                'db_table': 'free_enhances_limit',
            },
        ),
        migrations.DeleteModel(
            name='AnonymousUserEnhancesLimit',
        ),
    ]
