# Generated by Django 4.2.5 on 2023-10-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picsart', '0006_freeenhanceslimit_delete_anonymoususerenhanceslimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoususerfunctionsusagecounter',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='anonymoususerfunctionsusagecounter',
            name='ip_address_or_token',
            field=models.CharField(default=1, max_length=250, unique=True, verbose_name='IP Address'),
            preserve_default=False,
        ),
    ]
