from django.urls import path

from .views import (StripeWebhookAPIView,
                    StripeConfigAPIView,
                    CreateStripeCheckoutSessionAPIView,
                    CreateUserToMakePaymentAPIView,
                    CreatePayPalOrderAPIView,
                    PlansAPIVIew,
                    CreatePayPalForeignOrderAPIView,
                    CompleteForeignOrderByPayPalOrderID,
                    CreateStripeForeignCheckoutSessionAPIView,
                    CompleteOrderByPayPalOrderID,
                    PlanDetailAPIView,
                    UserOrders,
                    CancelPayPalOrderByIDAPIView,
                    StripeCancelOrderAPIView,
                    CancelForeignOrderByPayPalOrderID,
                    StripeCancelForeignOrderAPIView,
                    StripeSuccessAPIView,
                    StripeForeignSuccessAPIView)

urlpatterns = [
    path('plans/', PlansAPIVIew.as_view()),
    path('plans/<int:pk>/', PlanDetailAPIView.as_view()),
    path('user_orders/', UserOrders.as_view()),
    path('create_user_for_subscription/',
         CreateUserToMakePaymentAPIView.as_view()),
    path('stripe/config/', StripeConfigAPIView.as_view()),
    path('stripe/webhook/', StripeWebhookAPIView.as_view()),
    path('stripe/create_checkout_session/<int:plan_id>/',
         CreateStripeCheckoutSessionAPIView.as_view()),
    path('stripe/cancel_order/<str:cancel_id>/', StripeCancelOrderAPIView.as_view()),
    path('stripe/success_order/<str:success_id>/', StripeSuccessAPIView.as_view()),
    path('stripe/foreign/create_checkout_session/', CreateStripeForeignCheckoutSessionAPIView.as_view()),
    path('stripe/foreign/cancel_order/', StripeCancelForeignOrderAPIView.as_view()),
    path('stripe/foreign/success_order/<str:success_id>/', StripeForeignSuccessAPIView.as_view()),
    path('paypal/create_order/<int:plan_id>/', CreatePayPalOrderAPIView.as_view()),
    path('paypal/complete_order/<str:order_id>/', CompleteOrderByPayPalOrderID.as_view()),
    path('paypal/cancel_order/<str:order_id>/', CancelPayPalOrderByIDAPIView.as_view()),
    path('paypal/foreign/create_order/', CreatePayPalForeignOrderAPIView.as_view()),
    path('paypal/foreign/complete_order/<str:order_id>/', CompleteForeignOrderByPayPalOrderID.as_view()),
    path('paypal/foreign/cancel_order/<str:order_id>/', CancelForeignOrderByPayPalOrderID.as_view())
]
