# Generated by Django 4.2.5 on 2023-09-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_plan_remove_usersubscription_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default=1, max_length=15000, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
