# Generated by Django 4.2.5 on 2023-10-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_usersubscription_paypal_subscription_cancel_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='ends_at',
            new_name='next_pay_time',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='started_at',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription starting date'),
        ),
    ]
