# Generated by Django 4.2.5 on 2023-10-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0012_alter_usersubscription_payment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(max_length=150,
                                   choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('CANCELED', 'CANCELED'),
                                            ('EXPIRED', 'EXPIRED'), ('APPROVED', 'APPROVED'),
                                            ('APPROVAL_PENDING', 'APPROVAL_PENDING')], default=1,
                                   verbose_name='Subscription status'),
            preserve_default=False,
        ),
    ]
