# Generated by Django 4.2.5 on 2023-10-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_delete_stripeproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='period',
        ),
    ]
