# Generated by Django 4.2.5 on 2023-10-06 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan', verbose_name='Plan'),
        ),
    ]
