# Generated by Django 4.2.5 on 2023-09-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Plan/Subscription name')),
                ('price', models.IntegerField(verbose_name='Price in $')),
                ('period', models.CharField(max_length=150, verbose_name='Price per (month, 3 months, 6 months, year etc.)')),
                ('up_scales_count', models.IntegerField(default=100, verbose_name='Up scales count')),
                ('bg_deletions_count', models.IntegerField(default=100, verbose_name='Background deletions count')),
                ('jpg_artifacts_deletions_count', models.IntegerField(default=100, verbose_name='JPEG artifacts deletions count')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscription',
            },
        ),
    ]
