# Generated by Django 4.2.5 on 2023-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_period_in_months_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'Users Subscriptions'},
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription end date'),
        ),
    ]
