# Generated by Django 4.2.5 on 2023-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_usersubscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='PayPal product name')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(max_length=50, verbose_name='Type of product')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(default=1, max_length=5000, verbose_name='Stripe price ID'),
            preserve_default=False,
        ),
    ]
