# Generated by Django 4.2.5 on 2023-09-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paypalproduct_subscription_stripe_price_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paypalproduct',
            options={'verbose_name': 'product', 'verbose_name_plural': 'PayPal Products'},
        ),
        migrations.RemoveField(
            model_name='paypalproduct',
            name='type',
        ),
        migrations.AddField(
            model_name='paypalproduct',
            name='home_url',
            field=models.URLField(default=1, verbose_name='Home url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paypalproduct',
            name='image_url',
            field=models.URLField(default=1, verbose_name='Image url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paypalproduct',
            name='product_id',
            field=models.CharField(default=1, max_length=350, verbose_name='PayPal product ID'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='paypalproduct',
            table='paypal_product',
        ),
    ]
