# Generated by Django 4.2.5 on 2023-09-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paypalproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=450, null=True, verbose_name='PayPal subscription id'),
        ),
    ]
