# Generated by Django 4.2.5 on 2023-09-30 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_usersubscription_paypal_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Plan name')),
                ('price', models.IntegerField(verbose_name='Price in $')),
                ('period', models.CharField(max_length=150, verbose_name='Price per (month, 3 months, 6 months, year etc.)')),
                ('period_in_months', models.IntegerField(verbose_name='Period in months (required)')),
                ('up_scales_count', models.IntegerField(default=100, verbose_name='Up scales count')),
                ('bg_deletions_count', models.IntegerField(default=100, verbose_name='Background deletions count')),
                ('jpg_artifacts_deletions_count', models.IntegerField(default=100, verbose_name='JPEG artifacts deletions count')),
                ('stripe_price_id', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stripe price ID')),
                ('paypal_plan_id', models.CharField(blank=True, max_length=350, null=True, verbose_name='PayPal plan Id')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'plans',
            },
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.plan', verbose_name='Subscription'),
            preserve_default=False,
        ),
    ]
