# Generated by Django 4.2.5 on 2023-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='paypal_subscription_cancel_link',
            field=models.URLField(blank=True, null=True, verbose_name='PayPal subscription cancel link'),
        ),
    ]
