# Generated by Django 4.2.5 on 2023-10-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_rename_ends_at_usersubscription_next_pay_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='payment_service',
            field=models.IntegerField(default=1, verbose_name='Payment service'),
            preserve_default=False,
        ),
    ]
