# Generated by Django 4.2.5 on 2023-10-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_usersubscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalproduct',
            name='product_id',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='PayPal product ID'),
        ),
    ]
