# Generated by Django 4.2.5 on 2023-10-14 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0020_alter_usersubscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CANCELED', 'CANCELED'), ('COMPLETED', 'COMPLETED')], max_length=45, verbose_name='Order status')),
                ('payment_service', models.CharField(choices=[('PAYPAL', 'PAYPAL'), ('STRIPE', 'STRIPE')], max_length=45, verbose_name='Payment service')),
                ('paypal_order_id', models.CharField(max_length=150, verbose_name='PayPal order id')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.plan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
