# Generated by Django 4.2.5 on 2023-10-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_alter_order_paypal_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Stripe session id'),
        ),
    ]
