# Generated by Django 4.2.5 on 2023-10-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_foreignorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayPalProduct',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
