# Generated by Django 4.2.5 on 2023-10-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_delete_paypalproduct_delete_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='paypal_plan_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='period_in_months',
        ),
    ]
