# Generated by Django 4.2.5 on 2023-10-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_foreignorder_paypal_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignorder',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
