# Generated by Django 4.2.5 on 2023-10-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_foreignorder_is_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignorder',
            name='is_succeed',
            field=models.BooleanField(default=False),
        ),
    ]
