# Generated by Django 4.2.5 on 2023-10-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_foreignorder_is_succeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreignorder',
            old_name='is_failed',
            new_name='is_ended',
        ),
        migrations.RemoveField(
            model_name='foreignorder',
            name='is_succeed',
        ),
    ]
