# Generated by Django 4.2.5 on 2023-10-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
