# Generated by Django 4.2.5 on 2023-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_foreignorder_stripe_success_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_success_id',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Stripe success ID'),
        ),
    ]
